In [17]:
import numpy as np

def Gauss_Seidel(A, b, N):
 i = 0
 x0 = np.array([1, 1, 1])
 while (i < int(N)):
  matrix_e = np.array([[5,0,0], [-2,4,0], [2,-2,5]])
  matrix_e_inverse = np.linalg.inv(matrix_e)
  r = b - np.dot(A, x0)
  x1 = x0 + np.dot(matrix_e_inverse, r)
  print (x1)
  x0 = x1
  i = i + 1

def main():
  A = np.array([
    [5, -1, 3],
    [-2, 4, -1],
    [2, -2, 5]
])
  b = np.array([14, 2, 10])
  N = input("Insert the number of iterations here:")
  Gauss_Seidel(A,b,N)

main()

Insert the number of iterations here:15
[2.4  1.95 1.82]
[2.098  2.004  1.9624]
[2.02336  2.00228  1.991568]
[2.0055152  2.0006496  1.99805376]
[2.00129766 2.00016227 1.99954584]
[2.00030495 2.00003894 1.99989359]
[2.00007163 2.00000921 1.99997503]
[2.00001682 2.00000217 1.99999414]
[2.00000395 2.00000051 1.99999862]
[2.00000093 2.00000012 1.99999968]
[2.00000022 2.00000003 1.99999992]
[2.00000005 2.00000001 1.99999998]
[2.00000001 2.         2.        ]
[2. 2. 2.]
[2. 2. 2.]
